silent! source $VIMRUNTIME/defaults.vim
packadd comment

colorscheme kuro

syntax on
filetype plugin indent on
highlight LineNr ctermfg=grey

set tabstop=4
set shiftwidth=4
set expandtab

set number
set number relativenumber

set backspace=indent,eol,start

set listchars=eol:$

autocmd BufWritePre * :%s/\s\+$//e
